version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ADMIN_USERNAME=brivaldo
      - ADMIN_PASSWORD=123
      - DATABASE_URI=sqlite:///app/instance/usersdb.sqlite3  
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_APP=main.py
      - SECRET_KEY=SECRET_KEY
    volumes:
      - ./app/instance:/app/instance 
